{% set name = "dataclassy" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataclassy-{{ version }}.tar.gz
  sha256: e5a08a304f5f31b35983d3d14e60f00240fbcb38b4aea49db7d19160958b9a3d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - dataclassy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/biqqles/dataclassy
  summary: A fast and flexible reimplementation of data classes
  license: MPL-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - spinoch
